# Generated by Django 5.1.15 on 2026-06-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ViewpointCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="カテゴリコード"
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="カテゴリ名")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
            ],
            options={
                "verbose_name": "観点カテゴリ",
                "verbose_name_plural": "観点カテゴリ",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Viewpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewpoint",
                    models.CharField(max_length=200, verbose_name="テスト観点"),
                ),
                ("technique", models.CharField(max_length=80, verbose_name="技法")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("always", "常時適用"),
                            ("field", "入力項目別"),
                            ("flag", "機能特性別"),
                            ("industry", "業種別"),
                        ],
                        max_length=12,
                        verbose_name="適用契機",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="項目型(email等) / 特性(money等) / 業種(finance等)",
                        max_length=40,
                        verbose_name="適用キー",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewpoints",
                        to="knowledge.viewpointcategory",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "テスト観点",
                "verbose_name_plural": "テスト観点",
                "ordering": ["category__order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DefectPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_id",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="パターンID"
                    ),
                ),
                (
                    "pattern",
                    models.CharField(max_length=160, verbose_name="欠陥パターン"),
                ),
                (
                    "example",
                    models.CharField(blank=True, max_length=240, verbose_name="典型例"),
                ),
                (
                    "prevention",
                    models.CharField(blank=True, max_length=240, verbose_name="予防策"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defect_patterns",
                        to="knowledge.viewpointcategory",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "欠陥パターン",
                "verbose_name_plural": "欠陥パターン",
                "ordering": ["pattern_id"],
            },
        ),
    ]
