# Generated by Django 5.1.15 on 2026-06-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewpoint",
            name="authority",
            field=models.CharField(
                blank=True,
                help_text="この観点の裏付けとなる標準・ガイドライン（ISO/ISTQB/NIST/IPA等）",
                max_length=120,
                verbose_name="根拠標準",
            ),
        ),
    ]
