# Generated by Django 5.1.15 on 2026-06-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical（システム停止・データ破損）"),
                            ("Major", "Major（主要機能が動作不可）"),
                            ("Minor", "Minor（機能は動くが一部不具合）"),
                            ("Cosmetic", "Cosmetic（見た目・微細な問題）"),
                        ],
                        default="Major",
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("単体テスト", "単体テスト"),
                            ("結合テスト", "結合テスト"),
                            ("システムテスト", "システムテスト"),
                            ("UAT", "UAT"),
                            ("本番", "本番"),
                        ],
                        default="システムテスト",
                        max_length=20,
                        verbose_name="検出フェーズ",
                    ),
                ),
                (
                    "root_cause",
                    models.CharField(
                        choices=[
                            ("仕様漏れ", "仕様漏れ"),
                            ("実装誤り", "実装誤り"),
                            ("設計誤り", "設計誤り"),
                            ("テスト漏れ", "テスト漏れ"),
                            ("環境問題", "環境問題"),
                            ("外部要因", "外部要因"),
                        ],
                        default="実装誤り",
                        max_length=20,
                        verbose_name="根本原因",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="概要・再現手順"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Fixed", "Fixed"),
                            ("Closed", "Closed"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Open",
                        max_length=12,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "欠陥",
                "verbose_name_plural": "欠陥",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
