/* data.js — サービスカタログ定義とメニュー構造
 * kind: 'catalog'（人的支援サービス＝詳細表示） / 'tool'（実working MVPツール）
 */

const SERVICES = {
  /* ── 品質PMO（カタログ：人的支援サービス） ── */
  consultant: {
    icon: '👔', iconBg: '#e8edf8', group: 'quality', kind: 'catalog',
    title: 'コンサルタント派遣', category: '品質PMO › プロフェッショナル支援',
    breadcrumb: ['品質PMO', '品質評価支援軸', 'プロフェッショナル支援', 'コンサルタント派遣'],
    desc: '豊富な経験を持つ品質コンサルタントを派遣し、現場に入り込んで課題を特定・解決します。',
    features: [
      { icon: '🔍', title: '課題アセスメント', desc: '品質課題を多角的に分析し優先度付けします' },
      { icon: '🤝', title: '伴走支援', desc: 'チームに入って実務レベルで支援します' },
      { icon: '📊', title: '定量的改善', desc: 'KPIを設定し進捗を可視化します' },
      { icon: '🔄', title: '知識移転', desc: '自走できるようノウハウを移転します' },
    ],
    steps: ['ヒアリング', '課題分析', '改善計画', '現場支援', '効果測定'],
    tags: ['品質改善', 'PMO支援', 'ISO 25010'],
    cta: 'コンサルタント派遣について相談する',
  },
  planning: {
    icon: '📋', iconBg: '#e8edf8', group: 'quality', kind: 'catalog',
    title: '各種策定支援', category: '品質PMO › プロフェッショナル支援',
    breadcrumb: ['品質PMO', '品質評価支援軸', 'プロフェッショナル支援', '各種策定支援'],
    desc: 'テスト計画書・品質計画書・プロセス定義書などをISO 29119/ISTQB準拠で策定支援します。',
    features: [
      { icon: '📝', title: 'テスト計画策定', desc: 'ISO 29119準拠の計画書を作成します' },
      { icon: '⚙️', title: 'プロセス定義', desc: '組織に合わせた品質プロセスを定義します' },
      { icon: '✅', title: '品質基準設計', desc: '終了基準・受入条件を明確化します' },
      { icon: '🗂️', title: 'テンプレ整備', desc: '再利用可能な雛形を整備します' },
    ],
    steps: ['ヒアリング', 'ドラフト', 'レビュー', '承認・展開'],
    tags: ['ISO 29119', 'ISTQB', 'プロセス定義'],
    cta: '策定支援について相談する',
  },
  impl: {
    icon: '⚡', iconBg: '#e8edf8', group: 'quality', kind: 'catalog',
    title: '実装推進支援', category: '品質PMO › プロフェッショナル支援',
    breadcrumb: ['品質PMO', '品質評価支援軸', 'プロフェッショナル支援', '実装推進支援'],
    desc: '品質改善施策・新プロセスの実装フェーズを推進し、計画を確実に実行へ移します。',
    features: [
      { icon: '🚀', title: '推進管理', desc: '実装タスクの進捗とボトルネックを管理します' },
      { icon: '🛠️', title: 'ツール導入', desc: 'ツールの選定・導入・定着を支援します' },
      { icon: '👥', title: '関係者調整', desc: '合意形成を円滑に進めます' },
      { icon: '📈', title: '定着化', desc: '新プロセスの定着までフォローします' },
    ],
    steps: ['計画確認', '準備', 'パイロット', '本展開', '定着確認'],
    tags: ['変革管理', 'プロセス改善', 'ツール導入'],
    cta: '実装推進支援について相談する',
  },
  advisor: {
    icon: '🎯', iconBg: '#e8edf8', group: 'quality', kind: 'catalog',
    title: '顧問型支援', category: '品質PMO › プロフェッショナル支援',
    breadcrumb: ['品質PMO', '品質評価支援軸', 'プロフェッショナル支援', '顧問型支援'],
    desc: '継続的な顧問契約により、中長期の品質向上を伴走支援します。',
    features: [
      { icon: '📅', title: '月次レビュー', desc: '定期的に品質状況をレビューします' },
      { icon: '💬', title: '随時相談', desc: '品質課題に素早く対応します' },
      { icon: '🗺️', title: '品質ロードマップ', desc: '中長期の向上計画を策定します' },
      { icon: '🏅', title: '組織能力向上', desc: '品質マインドを底上げします' },
    ],
    steps: ['契約', '初期診断', '月次レビュー', '改善推進', '継続改善'],
    tags: ['継続支援', '顧問契約', '品質戦略'],
    cta: '顧問型支援について相談する',
  },
  education: {
    icon: '🎓', iconBg: '#fff3e0', group: 'quality', kind: 'catalog',
    title: '教育・示唆', category: '品質PMO › 品質評価支援軸',
    breadcrumb: ['品質PMO', '品質評価支援軸', '教育・示唆'],
    desc: 'ISTQBを軸にした体系的教育から現場ワークショップまで、品質教育を提供します。',
    features: [
      { icon: '📚', title: 'ISTQB研修', desc: 'Foundation〜Advanced対応の研修' },
      { icon: '🖥️', title: 'ハンズオン', desc: '実ツール・事例を使う実践研修' },
      { icon: '💡', title: '品質思考醸成', desc: '品質を作り込む文化を根付かせます' },
      { icon: '📊', title: '習熟度評価', desc: 'before/afterで効果を可視化します' },
    ],
    steps: ['ニーズ把握', '設計', '研修', '演習', '効果測定'],
    tags: ['ISTQB', 'トレーニング', '人材育成'],
    cta: '教育プログラムについて相談する',
  },
  project: {
    icon: '📌', iconBg: '#fce4ec', group: 'quality', kind: 'catalog',
    title: 'プロジェクト推進', category: '品質PMO',
    breadcrumb: ['品質PMO', 'プロジェクト推進'],
    desc: 'スケジュール・リスク・ステークホルダー管理を品質視点でワンストップ支援します。',
    features: [
      { icon: '📆', title: 'スケジュール管理', desc: 'WBS・ガントの作成と可視化を支援します' },
      { icon: '⚠️', title: 'リスク管理', desc: 'リスクの特定・評価・対策を実施します' },
      { icon: '📣', title: '報告体制', desc: '報告ラインとフォーマットを整備します' },
      { icon: '🔗', title: '横断調整', desc: '部門・チーム間の調整を円滑化します' },
    ],
    steps: ['計画', 'キックオフ', '推進', '課題対応', 'クローズ'],
    tags: ['PM', 'PMO', 'リスク管理', 'WBS'],
    cta: 'プロジェクト推進支援について相談する',
  },
  'test-promo': {
    icon: '🧪', iconBg: '#e8f5e9', group: 'quality', kind: 'catalog',
    title: 'テスト推進', category: '品質PMO',
    breadcrumb: ['品質PMO', 'テスト推進'],
    desc: 'テストマネージャーとして計画・実行・報告を推進し、リリース判定まで支援します。',
    features: [
      { icon: '📋', title: 'テスト計画管理', desc: '立案から承認まで一気通貫で管理します' },
      { icon: '🔬', title: '実施管理', desc: '進捗・カバレッジを管理します' },
      { icon: '🚦', title: '品質ゲート', desc: 'リリース判定基準を運用します' },
      { icon: '📊', title: 'テスト報告', desc: 'ISO 29119準拠のレポートを作成します' },
    ],
    steps: ['計画', '設計', '実施', '分析', 'リリース判定'],
    tags: ['テスト管理', 'ISO 29119', '品質ゲート'],
    cta: 'テスト推進支援について相談する',
  },
  'process-diag': {
    icon: '🩺', iconBg: '#e8edf8', group: 'quality', kind: 'catalog',
    title: 'プロセス診断', category: '品質PMO › 品質評価支援軸',
    breadcrumb: ['品質PMO', '品質評価支援軸', 'プロセス診断'],
    desc: '開発・テストプロセスの成熟度を客観指標で診断し、改善の優先度を提示します。',
    features: [
      { icon: '📐', title: '成熟度評価', desc: 'TMMi/TPI観点でプロセスを評価します' },
      { icon: '🔎', title: 'ギャップ分析', desc: '理想と現状の差分を可視化します' },
      { icon: '🎯', title: '改善優先度', desc: '投資対効果で施策を順位付けします' },
      { icon: '🗺️', title: '改善ロードマップ', desc: '段階的な改善計画を策定します' },
    ],
    steps: ['現状調査', '成熟度評価', 'ギャップ分析', '改善提案', '報告'],
    tags: ['プロセス診断', 'TMMi', 'TPI', '成熟度'],
    cta: 'プロセス診断について相談する',
  },
  'tpi-next': {
    icon: '📈', iconBg: '#e8edf8', group: 'quality', kind: 'catalog',
    title: 'テストプロセス改善', category: '品質PMO › 品質評価支援軸',
    breadcrumb: ['品質PMO', '品質評価支援軸', 'テストプロセス改善'],
    desc: '診断結果に基づきテストプロセスを継続的に改善し、品質とスピードを両立させます。',
    features: [
      { icon: '🔄', title: '継続的改善', desc: 'PDCAでプロセスを回します' },
      { icon: '📊', title: 'メトリクス管理', desc: '欠陥密度・工数などを定点観測します' },
      { icon: '⚙️', title: '標準化', desc: '再現性のある手順へ標準化します' },
      { icon: '🏅', title: '定着支援', desc: '改善を組織文化として根付かせます' },
    ],
    steps: ['ベースライン', '改善設計', '試行', '展開', '効果測定'],
    tags: ['プロセス改善', 'メトリクス', '標準化'],
    cta: 'テストプロセス改善について相談する',
  },

  /* ── 第三者検証（受託テスト：検証実行サービス。カタログ） ── */
  'test-outsource': {
    icon: '🧾', iconBg: '#ede7f6', group: 'verify', kind: 'catalog',
    title: 'ソフトウェアテスト受託', category: '第三者検証 › テスト実行',
    breadcrumb: ['第三者検証', 'テスト実行', 'ソフトウェアテスト受託'],
    desc: '中立な第三者の立場で、テスト設計から実行・報告までを一括受託します。',
    features: [
      { icon: '🎯', title: '中立的検証', desc: '開発から独立した視点で検証します' },
      { icon: '🧪', title: '設計〜実行', desc: 'テスト設計から実施まで請け負います' },
      { icon: '📋', title: 'エビデンス整備', desc: '監査に耐える証跡を残します' },
      { icon: '📊', title: '品質報告', desc: 'リリース判断材料を提供します' },
    ],
    steps: ['要件把握', 'テスト設計', '環境構築', '実行', '報告'],
    tags: ['第三者検証', '受託テスト', 'テスト実行', 'エビデンス'],
    cta: 'テスト受託について相談する',
  },
  'embedded-verify': {
    icon: '🔧', iconBg: '#ede7f6', group: 'verify', kind: 'catalog',
    title: '組込み・IoT検証', category: '第三者検証 › テスト実行',
    breadcrumb: ['第三者検証', 'テスト実行', '組込み・IoT検証'],
    desc: '組込み機器・IoTデバイスの実機検証を、ハード/ソフト両面の知見で実施します。',
    features: [
      { icon: '📟', title: '実機検証', desc: '実デバイス上で動作を検証します' },
      { icon: '🔌', title: '通信・連携', desc: 'プロトコル/連携の整合を確認します' },
      { icon: '🌡️', title: '環境試験', desc: '温度・負荷など環境条件を考慮します' },
      { icon: '⏱️', title: 'リアルタイム性', desc: '応答時間・タイミングを検証します' },
    ],
    steps: ['仕様分析', 'テスト設計', '実機準備', '検証', '報告'],
    tags: ['組込み', 'IoT', '実機検証', 'リアルタイム'],
    cta: '組込み・IoT検証について相談する',
  },
  'sap-verify': {
    icon: '🏢', iconBg: '#ede7f6', group: 'verify', kind: 'catalog',
    title: 'SAP・業務システム検証', category: '第三者検証 › テスト実行',
    breadcrumb: ['第三者検証', 'テスト実行', 'SAP・業務システム検証'],
    desc: 'SAP等のERP・基幹業務システムの導入/更改に伴う検証を専門知見で支援します。',
    features: [
      { icon: '🔗', title: '業務フロー検証', desc: 'エンドツーエンドの業務を検証します' },
      { icon: '🔁', title: '回帰テスト', desc: '更改時の影響範囲を検証します' },
      { icon: '🧮', title: 'データ整合', desc: '会計・在庫データの整合を確認します' },
      { icon: '🌐', title: '多拠点・多通貨', desc: 'グローバル要件を検証します' },
    ],
    steps: ['業務理解', 'シナリオ設計', 'データ準備', '検証', '報告'],
    tags: ['SAP', 'ERP', '基幹システム', '業務検証'],
    cta: 'SAP・業務システム検証について相談する',
  },
  'nonfunctional': {
    icon: '⚡', iconBg: '#ede7f6', group: 'verify', kind: 'catalog',
    title: '負荷・性能・非機能テスト', category: '第三者検証',
    breadcrumb: ['第三者検証', '負荷・性能・非機能テスト'],
    desc: '負荷・性能・信頼性・可用性など非機能要件を定量的に検証します。',
    features: [
      { icon: '📊', title: '負荷試験', desc: '想定/限界負荷での挙動を測定します' },
      { icon: '⏲️', title: '性能測定', desc: '応答時間・スループットを計測します' },
      { icon: '🛡️', title: '信頼性', desc: '長時間稼働・障害復旧を検証します' },
      { icon: '📈', title: 'ボトルネック分析', desc: '性能上の制約点を特定します' },
    ],
    steps: ['要件定義', 'シナリオ設計', '環境構築', '測定', '分析・報告'],
    tags: ['負荷テスト', '性能', '非機能', '信頼性'],
    cta: '非機能テストについて相談する',
  },

  /* ── AIサービス（実working MVPツール。AIなし＝決定的アルゴリズム） ── */
  'doc-verify': {
    icon: '📄', iconBg: '#e8f5e9', group: 'ai', kind: 'tool', tool: 'docVerifier',
    title: 'ドキュメント検証', category: 'AIサービス › AIツール',
    breadcrumb: ['AIサービス', 'AIツール', 'ドキュメント検証'],
    desc: 'ルールベース校正（textlint/RedPen系）で曖昧語・冗長文・必須節欠落を検出します。',
    tags: ['校正', '曖昧語検出', 'ISTQB severity'],
  },
  trace: {
    icon: '🔗', iconBg: '#e8f5e9', group: 'ai', kind: 'tool', tool: 'traceability',
    product: 'ConTrack',
    title: 'トレーサビリティ', category: 'AIサービス › AIツール',
    breadcrumb: ['AIサービス', 'AIツール', 'トレーサビリティ'],
    desc: 'トレーサビリティ管理ツール「ConTrack」相当。要件↔テストのRTMを生成し、カバレッジ・未カバー要件・孤立テストを算出します。',
    tags: ['ConTrack', 'RTM', 'カバレッジ', '影響分析'],
  },
  'plan-ai': {
    icon: '🗓️', iconBg: '#e8f5e9', group: 'ai', kind: 'tool', tool: 'testPlan',
    title: '計画策定', category: 'AIサービス › AIツール',
    breadcrumb: ['AIサービス', 'AIツール', '計画策定'],
    desc: 'ISO 29119-3構造のテスト計画書をフォーム入力から自動生成します。',
    tags: ['ISO 29119', 'テスト計画', '自動生成'],
  },
  'test-design': {
    icon: '✏️', iconBg: '#e8f5e9', group: 'ai', kind: 'tool', tool: 'testDesign',
    product: 'GIHOZ',
    title: 'テスト設計', category: 'AIサービス › AIツール',
    breadcrumb: ['AIサービス', 'AIツール', 'テスト設計'],
    desc: 'テスト技法ツール「GIHOZ」相当。ISTQB技法（境界値・同値分割・ペアワイズ）でテストケースを自動生成します。',
    tags: ['GIHOZ', '境界値', '同値分割', 'ペアワイズ', 'ISTQB'],
  },
  uiux: {
    icon: '🖥️', iconBg: '#e8f5e9', group: 'ai', kind: 'tool', tool: 'uiuxChecker',
    title: 'UI/UX検証', category: 'AIサービス › AIツール',
    breadcrumb: ['AIサービス', 'AIツール', 'UI/UX検証'],
    desc: 'axe-core（WCAG）＋決定的ヒューリスティックでアクセシビリティを検証します。',
    tags: ['axe-core', 'WCAG', 'アクセシビリティ'],
  },
  'test-auto': {
    icon: '🤖', iconBg: '#e3f2fd', group: 'ai', kind: 'tool', tool: 'testAuto',
    title: 'テスト自動化（UI・API・BAT）', category: 'AIサービス › 自動化サービス',
    breadcrumb: ['AIサービス', '自動化サービス', 'テスト自動化（UI・API・BAT）'],
    desc: 'Playwright / pytest+requests / bats のテストscaffoldを生成します。',
    tags: ['Playwright', 'pytest', 'bats', 'scaffold'],
  },
  cicd: {
    icon: '🔄', iconBg: '#e3f2fd', group: 'ai', kind: 'tool', tool: 'cicd',
    title: 'CI/CD構築', category: 'AIサービス › 自動化サービス',
    breadcrumb: ['AIサービス', '自動化サービス', 'CI/CD構築'],
    desc: 'ランタイム別にGitHub Actionsのパイプライン（build→test→gate→deploy）を生成します。',
    tags: ['GitHub Actions', 'CI/CD', 'YAML生成'],
  },
  'viewpoint-kb': {
    icon: '🔬', iconBg: '#f3e5f5', group: 'ai', kind: 'tool', tool: 'viewpointBrowser',
    title: '観点ライブラリ', category: 'AIサービス › 知識資産',
    breadcrumb: ['AIサービス', '知識資産', '観点ライブラリ'],
    desc: 'テスト観点ナレッジベースを閲覧・検索します。業種別・カテゴリ別フィルタと欠陥パターンDBを内包します。',
    tags: ['観点ライブラリ', '欠陥パターン', 'ナレッジベース', 'ISTQB'],
  },
  'defect-mgr': {
    icon: '🐛', iconBg: '#fce4ec', group: 'ai', kind: 'tool', tool: 'defectMgr',
    title: '欠陥管理', category: 'AIサービス › AIツール',
    breadcrumb: ['AIサービス', 'AIツール', '欠陥管理'],
    desc: 'ISTQBのseverityで欠陥を登録・追跡します。localStorageで永続化、CSVエクスポート対応。',
    tags: ['欠陥管理', 'ISTQB severity', 'バグトラッキング', 'CSV'],
  },
  'testra': {
    icon: '🦾', iconBg: '#e3f2fd', group: 'ai', kind: 'catalog',
    product: 'TESTRA',
    title: 'テスト設計エージェント', category: 'AIサービス › AI品質保証',
    breadcrumb: ['AIサービス', 'AI品質保証', 'テスト設計エージェント'],
    desc: '人×AIで品質保証するテスト設計エージェント「TESTRA」相当。仕様から観点を適用し、テスト設計をAIが支援します。',
    features: [
      { icon: '🤝', title: '人×AI協調', desc: '人の観点とAIの網羅性を組み合わせます' },
      { icon: '🧩', title: '観点適用', desc: '観点ライブラリを仕様に適用します' },
      { icon: '⚡', title: '設計自動化', desc: 'テスト条件・ケースを高速に生成します' },
      { icon: '👁️', title: 'レビュー支援', desc: '抜け漏れをAIが指摘します' },
    ],
    steps: ['仕様入力', '観点適用', '設計生成', '人によるレビュー', '確定'],
    tags: ['TESTRA', 'AIテスト設計', '人×AI', '観点適用'],
    cta: 'テスト設計エージェントについて相談する',
  },
  'static-analysis': {
    icon: '🔍', iconBg: '#e8f5e9', group: 'ai', kind: 'catalog',
    title: 'ソースコード静的解析', category: 'AIサービス › 品質分析',
    breadcrumb: ['AIサービス', '品質分析', 'ソースコード静的解析'],
    desc: '静的解析でコードの欠陥・複雑度・規約違反を検出し、保守性リスクを可視化します。',
    features: [
      { icon: '🐞', title: '潜在欠陥検出', desc: 'Null参照・リーク等を静的に検出します' },
      { icon: '📏', title: '複雑度計測', desc: '循環的複雑度などを測定します' },
      { icon: '📐', title: '規約チェック', desc: 'コーディング規約準拠を確認します' },
      { icon: '📊', title: '品質可視化', desc: 'ホットスポットを定量化します' },
    ],
    steps: ['対象選定', '解析実行', 'トリアージ', '是正提案', '報告'],
    tags: ['静的解析', 'SAST', 'コード品質', '保守性'],
    cta: '静的解析について相談する',
  },
  'oss-risk': {
    icon: '📦', iconBg: '#e8f5e9', group: 'ai', kind: 'catalog',
    title: 'OSSリスク管理', category: 'AIサービス › 品質分析',
    breadcrumb: ['AIサービス', '品質分析', 'OSSリスク管理'],
    desc: '利用OSSのライセンス・既知脆弱性・保守状況を棚卸しし、サプライチェーンリスクを管理します。',
    features: [
      { icon: '📜', title: 'ライセンス管理', desc: 'ライセンス適合性を確認します' },
      { icon: '🛡️', title: '脆弱性照合', desc: '既知CVEとの照合を行います（SCA）' },
      { icon: '🧬', title: 'SBOM作成', desc: '部品表（SBOM）を整備します' },
      { icon: '🔔', title: '継続監視', desc: '新規脆弱性を継続的に追跡します' },
    ],
    steps: ['依存棚卸し', 'SCA解析', 'リスク評価', '対応計画', '監視'],
    tags: ['OSS', 'SCA', 'SBOM', 'サプライチェーン'],
    cta: 'OSSリスク管理について相談する',
  },
  'exploratory': {
    icon: '🧭', iconBg: '#e3f2fd', group: 'ai', kind: 'catalog',
    product: 'InsighTest',
    title: '探索的テスト支援', category: 'AIサービス › 効率化',
    breadcrumb: ['AIサービス', '効率化', '探索的テスト支援'],
    desc: '協調・探索型クラウドテストツール「InsighTest」相当。チャーター駆動の探索的テストで、スクリプト化しにくい不具合や気付きを発見します。',
    features: [
      { icon: '🗺️', title: 'チャーター設計', desc: '探索の狙いを明文化します' },
      { icon: '👥', title: '協調セッション', desc: 'チームで気付きを共有します' },
      { icon: '🐛', title: '不具合発見', desc: '想定外の欠陥を見つけ出します' },
      { icon: '📝', title: 'セッション記録', desc: '探索過程を証跡化します' },
    ],
    steps: ['チャーター作成', 'セッション実施', '記録', 'デブリーフ', '報告'],
    tags: ['InsighTest', '探索的テスト', 'チャーター', 'セッションベース'],
    cta: '探索的テスト支援について相談する',
  },
  'qa4ai': {
    icon: '🧠', iconBg: '#e3f2fd', group: 'ai', kind: 'catalog',
    title: 'AI製品の品質保証（QA4AI）', category: 'AIサービス › AI品質保証',
    breadcrumb: ['AIサービス', 'AI品質保証', 'AI製品の品質保証（QA4AI）'],
    desc: 'AI/機械学習を搭載した製品・サービスの品質を、AI特有の観点で評価・保証します。',
    features: [
      { icon: '🎲', title: '非決定性対応', desc: '確率的挙動を統計的に評価します' },
      { icon: '⚖️', title: '公平性・バイアス', desc: '出力の偏りを検査します' },
      { icon: '🛡️', title: '頑健性', desc: '敵対的入力・外れ値に対する堅牢性を検証します' },
      { icon: '📊', title: '精度評価', desc: 'データセットで精度・再現率を測定します' },
    ],
    steps: ['評価設計', 'データ準備', '評価実行', 'リスク分析', '報告'],
    tags: ['QA4AI', 'AI品質', '公平性', '頑健性'],
    cta: 'AI製品の品質保証について相談する',
  },
  'genai-qa': {
    icon: '✨', iconBg: '#e3f2fd', group: 'ai', kind: 'catalog',
    title: '生成AIアプリ品質保証', category: 'AIサービス › AI品質保証',
    breadcrumb: ['AIサービス', 'AI品質保証', '生成AIアプリ品質保証'],
    desc: 'LLM・生成AIアプリ特有のリスク（ハルシネーション/プロンプト注入等）を体系的に評価します。',
    features: [
      { icon: '🌫️', title: 'ハルシネーション', desc: '事実誤り・幻覚の発生率を測定します' },
      { icon: '💉', title: 'プロンプト注入', desc: '注入攻撃への耐性を検証します' },
      { icon: '🔒', title: '情報漏洩', desc: '機密・個人情報の漏えいを検査します' },
      { icon: '📐', title: '出力一貫性', desc: '回答の一貫性・再現性を評価します' },
    ],
    steps: ['リスク定義', '評価セット作成', '評価実行', '緩和提案', '報告'],
    tags: ['生成AI', 'LLM', 'ハルシネーション', 'プロンプト注入'],
    cta: '生成AIアプリ品質保証について相談する',
  },

  /* ── セキュリティ（脆弱性診断・トレーニング。カタログ） ── */
  'vuln-web': {
    icon: '🛡️', iconBg: '#ffebee', group: 'security', kind: 'catalog',
    product: 'Vex',
    title: 'Webアプリケーション脆弱性診断', category: 'セキュリティ',
    breadcrumb: ['セキュリティ', 'Webアプリケーション脆弱性診断'],
    desc: '脆弱性検査・診断ツール「Vex（Vulnerability Explorer）」相当。OWASP Top 10を含む観点でWebアプリの脆弱性を診断し、是正までを支援します。',
    features: [
      { icon: '🕷️', title: '脆弱性検出', desc: 'SQLi/XSS/認可不備等を検出します' },
      { icon: '📋', title: 'OWASP準拠', desc: 'OWASP Top 10/ASVSに沿って診断します' },
      { icon: '🎯', title: 'リスク評価', desc: 'CVSSで深刻度を評価します' },
      { icon: '🔧', title: '是正支援', desc: '修正方針と再診断を支援します' },
    ],
    steps: ['対象定義', '診断実施', 'リスク評価', '報告', '再診断'],
    tags: ['Vex', '脆弱性診断', 'OWASP', 'CVSS', 'Webセキュリティ'],
    cta: 'Web脆弱性診断について相談する',
  },
  'vuln-embedded': {
    icon: '📡', iconBg: '#ffebee', group: 'security', kind: 'catalog',
    title: '組込み・IoTセキュリティ診断', category: 'セキュリティ',
    breadcrumb: ['セキュリティ', '組込み・IoTセキュリティ診断'],
    desc: '組込み機器・IoTデバイスのファームウェア/通信/ハードウェア面のセキュリティを診断します。',
    features: [
      { icon: '💽', title: 'ファーム解析', desc: 'リバースエンジニアリングで解析します' },
      { icon: '📶', title: '通信診断', desc: '無線/有線プロトコルを検査します' },
      { icon: '🔌', title: 'ハード解析', desc: 'デバッグポート等の物理面を調査します' },
      { icon: '🚗', title: '車載・産業', desc: 'CAN等の産業プロトコルにも対応します' },
    ],
    steps: ['対象調査', '解析', '脆弱性評価', '報告', '是正支援'],
    tags: ['IoTセキュリティ', '組込み', 'ファームウェア', 'リバースエンジニアリング'],
    cta: '組込み・IoT診断について相談する',
  },
  'sec-training': {
    icon: '🎓', iconBg: '#ffebee', group: 'security', kind: 'catalog',
    title: 'セキュリティトレーニング', category: 'セキュリティ',
    breadcrumb: ['セキュリティ', 'セキュリティトレーニング'],
    desc: '実機ハンズオンで、組込みハッキング/脆弱性対策を体系的に学べる研修を提供します。',
    features: [
      { icon: '🖐️', title: 'ハンズオン', desc: '実機を使った実践演習を行います' },
      { icon: '🔓', title: '攻撃手法理解', desc: '攻撃者視点で弱点を学びます' },
      { icon: '🛡️', title: '防御設計', desc: 'セキュアな設計手法を習得します' },
      { icon: '📜', title: '修了評価', desc: '習熟度を評価し証明します' },
    ],
    steps: ['レベル把握', 'カリキュラム設計', '研修', '演習', '評価'],
    tags: ['セキュリティ研修', 'ハンズオン', '組込みハッキング', '人材育成'],
    cta: 'セキュリティトレーニングについて相談する',
  },
};

/* メニュー構造（ツリー）。リーフは SERVICES の id を参照。 */
const NAV_TREE = [
  {
    label: '品質PMO', icon: '🛡️', iconBg: '#e8edf8',
    children: [
      {
        label: '品質評価支援軸',
        children: [
          {
            label: 'プロフェッショナル支援',
            children: [
              { id: 'consultant' }, { id: 'planning' }, { id: 'impl' }, { id: 'advisor' },
            ],
          },
          { id: 'education' },
          { id: 'process-diag' },
          { id: 'tpi-next' },
        ],
      },
      { id: 'project' },
      { id: 'test-promo' },
    ],
  },
  {
    label: '第三者検証', icon: '🔍', iconBg: '#ede7f6',
    children: [
      {
        label: 'テスト実行',
        children: [
          { id: 'test-outsource' }, { id: 'embedded-verify' }, { id: 'sap-verify' },
        ],
      },
      { id: 'nonfunctional' },
    ],
  },
  {
    label: 'AIサービス', icon: '🤖', iconBg: '#e8f5e9',
    children: [
      {
        label: 'AIツール',
        children: [
          { id: 'doc-verify' }, { id: 'trace' }, { id: 'plan-ai' },
          { id: 'test-design' }, { id: 'uiux' }, { id: 'defect-mgr' },
        ],
      },
      {
        label: '品質分析',
        children: [{ id: 'static-analysis' }, { id: 'oss-risk' }],
      },
      {
        label: '効率化・自動化',
        children: [{ id: 'test-auto' }, { id: 'cicd' }, { id: 'exploratory' }],
      },
      {
        label: 'AI品質保証',
        children: [{ id: 'testra' }, { id: 'qa4ai' }, { id: 'genai-qa' }],
      },
      {
        label: '知識資産',
        children: [{ id: 'viewpoint-kb' }],
      },
    ],
  },
  {
    label: 'セキュリティ', icon: '🔒', iconBg: '#ffebee',
    children: [
      { id: 'vuln-web' }, { id: 'vuln-embedded' }, { id: 'sec-training' },
    ],
  },
];
