# Generated by Django 5.1.15 on 2026-06-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="スラッグ")),
                ("name", models.CharField(max_length=60, verbose_name="区分名")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="アイコン(絵文字)"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="ひとこと説明"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
            ],
            options={
                "verbose_name": "サービス区分",
                "verbose_name_plural": "サービス区分",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="グループ名")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="catalog.category",
                        verbose_name="区分",
                    ),
                ),
            ],
            options={
                "verbose_name": "サービスグループ",
                "verbose_name_plural": "サービスグループ",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="スラッグ")),
                ("title", models.CharField(max_length=80, verbose_name="サービス名")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="アイコン(絵文字)"
                    ),
                ),
                (
                    "summary",
                    models.CharField(max_length=220, verbose_name="概要（1行）"),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "product",
                    models.CharField(
                        blank=True,
                        help_text="ベリサーブ製品との対応（GIHOZ / ConTrack / Vex 等）",
                        max_length=40,
                        verbose_name="提供製品名",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("tool", "実務ツール（画面で実行できる）"),
                            ("catalog", "参照カタログ（手順・観点の解説）"),
                        ],
                        default="catalog",
                        max_length=10,
                        verbose_name="種別",
                    ),
                ),
                (
                    "tool_key",
                    models.CharField(
                        blank=True,
                        help_text="kind=tool のとき、tools アプリのどのツールを呼ぶか",
                        max_length=40,
                        verbose_name="ツールキー",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="タグ"),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=list, verbose_name="特徴カード"
                    ),
                ),
                (
                    "steps",
                    models.JSONField(
                        blank=True, default=list, verbose_name="支援フロー"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="catalog.category",
                        verbose_name="区分",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="catalog.servicegroup",
                        verbose_name="グループ",
                    ),
                ),
            ],
            options={
                "verbose_name": "サービス",
                "verbose_name_plural": "サービス",
                "ordering": ["order", "id"],
            },
        ),
    ]
